---
- apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
      - 'build-essential'
      - 'libssl-dev'

- get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v0.35.2/install.sh
    dest: /home/{{ansible_user}}/install.sh
    mode: '7777'

- shell: /home/{{ansible_user}}/install.sh

- shell: . /home/{{ansible_user}}/.profile

- file:
   path: /home/{{ansible_user}}/install.sh
   state: absent