---
- apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
        - 'gcc'
        - 'g++'
        - 'make'

- get_url:
    url: https://deb.nodesource.com/setup_10.x
    dest: /home/{{ansible_user}}/setup_10.x
    mode: '7777'

- shell: /home/{{ansible_user}}/setup_10.x

- apt:
    name: nodejs
    state: present

- file:
    path: /home/{{ansible_user}}/setup_10.x
    state: absent