# Add Docker official GPG key
- apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# Set up the stable repository
- apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable
    state: present
    update_cache: yes

# Install docker
- apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
        - 'docker-ce'
        - 'docker-ce-cli'
        - 'containerd.io'