---

- apt:
    name: "{{ item }}"
    state: present
  with_items:
    - 'software-properties-common'
    - 'apt-transport-https'
    - 'wget'

- apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present

- apt:
    name: code
    state: present