---

- apt:
    name: "{{ item }}"
    state: present
  with_items:
    - 'software-properties-common'
    - 'apt-transport-https'
    - 'wget'

- apt_key:
    url: https://packagecloud.io/AtomEditor/atom/gpgkey
    state: present

- apt_repository:
    repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
    state: present

- apt:
    name: atom
    state: present