---
- apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present

- apt_repository:
    repo: deb http://pkg.jenkins.io/debian-stable binary/
    state: present

- apt:
    name: jenkins
    state: present