---
# tasks file for python

- name: install software properties common
  apt:
    name: software-properties-common
    state: present
    update_cache: yes

- name: add repository
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: install python
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - 'python3.7'
    - 'python3.7-dev'
    - 'python3.7-venv'
    - 'python3'
    - 'python3-dev'
    - 'python3-venv'
    - 'python3-pip'
